# 🧠 01. NumPy Array Foundations & Memory Mechanics (Noob-Friendly Complete Guide)

### 💡 Mental Model: The Egg Carton vs. The Plastic Bag
* **Python List:** A loose plastic bag holding random object references. Slow & memory-heavy.
* **NumPy Array (`ndarray`):** An **egg carton** where every slot is identical in size and laid out consecutively in RAM. Fast & CPU-cache friendly!

---
### 📌 How this notebook is structured:
1. **Self-Documenting Names:** No single-letter variables (`m`, `v`, `a`, `x`). Every variable explains its exact role (e.g. `transaction_amounts`, `user_feature_matrix`).
2. **Atomic Concept Pairs:** Every concept has an isolated **Markdown explanation (What, Why, Mental Model)** followed immediately by a **short 3–5 line code cell**.

In [18]:
import numpy as np
print(f"🚀 NumPy {np.__version__} Ready!")

🚀 NumPy 1.26.4 Ready!


---
## 📁 Section 1: Array Creation Fundamentals


### 🔹 1.1: 1D Vector (Transaction Amounts)
**💡 What is it?** A single row of consecutive numbers in memory.
**🤔 Why use it?** Ideal for financial time-series, transaction streams, or customer balances.


In [19]:
transaction_amounts = np.array([10.50, 20.00, 35.25, 50.00], dtype=np.float64)
print('1D Transaction Array:', transaction_amounts)
print('Shape (Items)       :', transaction_amounts.shape)


1D Transaction Array: [10.5  20.   35.25 50.  ]
Shape (Items)       : (4,)


### 🔹 1.2: 2D Matrix (User Feature Grid: [Age, Balance, CreditScore])
**💡 What is it?** A 2D grid where rows represent samples/customers and columns represent features.
**🤔 Why use it?** The standard format for training ML models and tabular risk scoring.


In [20]:
user_feature_matrix = np.array([
    [25, 4500.0, 720],
    [34, 12000.0, 680]
], dtype=np.float64)
print('2D User Feature Matrix:\n', user_feature_matrix)
print('Shape (Rows, Cols)    :', user_feature_matrix.shape)


2D User Feature Matrix:
 [[   25.  4500.   720.]
 [   34. 12000.   680.]]
Shape (Rows, Cols)    : (2, 3)


### 🔹 1.3: 3D Tensor (Batches of Multi-Channel Sensor / Image Data)
**💡 What is it?** A stack of 2D matrices (Batches x Rows x Columns).
**🤔 Why use it?** Storing batches of image frames, multi-asset orderbooks, or 3D point clouds.


In [21]:
multi_batch_tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print('3D Batch Tensor:\n', multi_batch_tensor)
print('Tensor Shape (Batches, Rows, Cols):', multi_batch_tensor.shape)


3D Batch Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Tensor Shape (Batches, Rows, Cols): (2, 2, 2)


---
## 📁 Section 2: Factory Initializers (Allocating Structured Memory)


### 🔹 2.1: All-Zero Memory Grid with np.zeros()
**💡 What is it?** Allocates a clean memory block filled entirely with `0.0`.
**🤔 Why use it?** Pre-allocating accumulators and risk matrices before running loops.


In [ ]:
zero_initialized_weights = np.zeros((2, 4), dtype=np.float64)
print('Zero Initialized Weights Grid:\n', zero_initialized_weights)


Zero Initialized Weights Grid:
 [[0 0 0 0]
 [0 0 0 0]]


### 🔹 2.2: All-Ones Multiplicative Grid with np.ones()
**💡 What is it?** Allocates an array filled entirely with `1`.
**🤔 Why use it?** Baseline multiplier weights, identity scaling grids.


In [23]:
ones_scaling_mask = np.ones((2, 3), dtype=np.int32)
print('Ones Scaling Grid:\n', ones_scaling_mask)


Ones Scaling Grid:
 [[1 1 1]
 [1 1 1]]


### 🔹 2.3: Custom Constant Grid with np.full()
**💡 What is it?** Fills every slot with your chosen constant value.
**🤔 Why use it?** Initializing arrays with sentinel defaults like `-1` or penalty defaults like `999.0`.


In [24]:
default_penalty_grid = np.full((2, 3), fill_value=999.0)
print('Default Penalty Grid:\n', default_penalty_grid)


Default Penalty Grid:
 [[999. 999. 999.]
 [999. 999. 999.]]


### 🔹 2.4: Uninitialized High-Speed Buffer with np.empty()
**💡 What is it?** Allocates RAM *without* clearing previous memory contents.
**🤔 Why use it?** The fastest allocation method when you plan to immediately overwrite every element.


In [25]:
raw_buffer = np.empty((2, 2), dtype=np.float64)
print('Raw Buffer (Uninitialized RAM Junk):\n', raw_buffer)


Raw Buffer (Uninitialized RAM Junk):
 [[10.5  20.  ]
 [35.25 50.  ]]


---
## 📁 Section 3: Numerical Ranges & Sequences


### 🔹 3.1: Stepped Integer Sequence with np.arange()
**💡 What is it?** `np.arange(start, stop, step)` generates stepped numbers (stop is excluded).
**🤔 Why use it?** Like Python's `range()` but returns a contiguous C-array.


In [26]:
even_customer_ids = np.arange(0, 10, 2)
print('Even Customer ID Sequence:', even_customer_ids)


Even Customer ID Sequence: [0 2 4 6 8]


### 🔹 3.2: Linearly Spaced Grid with np.linspace()
**💡 What is it?** `np.linspace(start, stop, count)` creates exact evenly-spaced intervals (stop is INCLUDED).
**🤔 Why use it?** Sampling continuous time, drawing probability density charts, curve plotting.


In [27]:
sample_probability_grid = np.linspace(0.0, 1.0, 5)
print('Sample Probability Grid (5 Points):', sample_probability_grid)


Sample Probability Grid (5 Points): [0.   0.25 0.5  0.75 1.  ]


### 🔹 3.3: Logarithmic Grid with np.logspace()
**💡 What is it?** Generates points spaced exponentially on a base-10 scale ($10^{start}$ to $10^{stop}$).
**🤔 Why use it?** ML hyperparameter tuning grids (e.g. learning rates $10^{-3}$ to $10^1$).


In [28]:
learning_rate_schedule = np.logspace(-3, 0, 4)  # 0.001, 0.01, 0.1, 1.0
print('Learning Rate Tuning Schedule:', learning_rate_schedule)


Learning Rate Tuning Schedule: [0.001 0.01  0.1   1.   ]


### 🔹 3.4: Geometric Progression with np.geomspace()
**💡 What is it?** Geometric curve directly between specified bounds.
**🤔 Why use it?** Exponential decay grids, compound interest simulations.


In [29]:
compound_growth_grid = np.geomspace(100, 10000, 3)  # 100, 1000, 10000
print('Compound Growth Grid:', compound_growth_grid)


Compound Growth Grid: [  100.  1000. 10000.]


---
## 📁 Section 4: Special Structural Matrices


### 🔹 4.1: Identity Transformation Matrix with np.eye()
**💡 What is it?** Square matrix with `1.0` along the main diagonal and `0.0` everywhere else.
**🤔 Why use it?** Baseline identity linear transform that leaves vectors unchanged.


In [30]:
identity_transform_matrix = np.eye(3)
print('3x3 Identity Matrix:\n', identity_transform_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 🔹 4.2: Custom Diagonal Matrix with np.diag()
**💡 What is it?** Places a 1D vector along the diagonal of a 2D matrix.
**🤔 Why use it?** Constructing portfolio asset variance matrices, scaling dimensions.


In [31]:
portfolio_asset_variances = np.diag([0.04, 0.09, 0.16])
print('Portfolio Variance Matrix:\n', portfolio_asset_variances)


Portfolio Variance Matrix:
 [[0.04 0.   0.  ]
 [0.   0.09 0.  ]
 [0.   0.   0.16]]


---
## 📁 Section 5: Core Array Inspection Attributes


### 🔹 5.1: Inspecting Shape, Dtype, Itemsize & Total Bytes
**💡 What is it?** Instant metadata introspection on any NumPy array.
**🤔 Why use it?** Debugging tensor dimension mismatches and auditing RAM consumption.


In [32]:
user_dataset = np.ones((100, 5), dtype=np.float64)
print('.ndim     (Dimensions)  :', user_dataset.ndim)
print('.shape    (Rows, Cols)  :', user_dataset.shape)
print('.size     (Total Items) :', user_dataset.size)
print('.dtype    (Data Type)   :', user_dataset.dtype)
print('.itemsize (Bytes / Item):', user_dataset.itemsize)
print('.nbytes   (Total RAM)   :', user_dataset.nbytes)


.ndim     (Dimensions)  : 2
.shape    (Rows, Cols)  : (100, 5)
.size     (Total Items) : 500
.dtype    (Data Type)   : float64
.itemsize (Bytes / Item): 8
.nbytes   (Total RAM)   : 4000


---
## 📁 Section 6: Memory Views vs. Deep Copies


### 🔹 6.1: Slicing Shares Memory (Zero-Copy View)
**💡 What is it?** Slices point directly to the original array's memory buffer without copying.
**⚠️ Critical Note:** Mutating the slice mutates the parent array!


In [33]:
original_account_balances = np.array([100.0, 250.0, 300.0, 500.0])
window_view = original_account_balances[0:2]
window_view[0] = 999.0
print('Original Modified via View!:', original_account_balances)


Original Modified via View!: [999. 250. 300. 500.]


### 🔹 6.2: Explicit Deep Copy with .copy()
**💡 What is it?** Allocates completely fresh RAM for an independent duplicate.
**🤔 Why use it?** Safely altering a sub-array without risking changes to the raw source data.


In [34]:
original_account_balances = np.array([100.0, 250.0, 300.0, 500.0])
safe_clone = original_account_balances[0:2].copy()
safe_clone[0] = 999.0
print('Original Untouched:', original_account_balances)
print('Safe Clone Mutated:', safe_clone)


Original Untouched: [100. 250. 300. 500.]
Safe Clone Mutated: [999. 250.]
